import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./(globalComponents)/navbar";
import Footer from "./(globalComponents)/footer";
import Slider from "./(globalComponents)/slider";
import Hero1 from "./(globalComponents)/Hero1";
import ServiceHubs from "./(globalComponents)/HubCard";
import { Toaster } from "sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      // for light layout .
      data-theme="light"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="">
        <div className="">
          <Toaster richColors position="top-right"/>
          {children}
        </div>
      </body>
    </html>
  );
}
